from pathlib import Path

TITLE = "3*Huawei LUNA2000-2.0MWH-2H1"

#Data Config
START_DATE = "2023-01-01" #included
END_DATE = "2025-01-01" #excluded
PSEUDO_END_DATE = None #"2040-12-31 23:45:00+01:00"

##Battery Hardware
INITIAL_BATTERY_CAPACITY = 6.09  #MWh
SYSTEM_POWER = 3.0483 #MW (1MW = 1MWh/1h) # AC Seitig
LIFETIME_CYCLES = 6519  
MAX_CHARGE_RATE = SYSTEM_POWER * (15/60)  # Max MWH pro 15min
MAX_CYCLE_RATE = MAX_CHARGE_RATE / (2 * INITIAL_BATTERY_CAPACITY)  #pro 15min

EFFICIENCY_BAT = 0.949 # einseitiger Wirkungsgrad (jeweils Lade- und Entladeverluste)
EFFICIENCY_INVERTER = 0.99
EFFICIENCY_COOLING = 0.99
EFFICIENCY_TRANSFORMER = 0.99
EFFICIENCY_DISTRIBUTION = 0.995 #Kabel etc.
EFFICIENCY_REST = EFFICIENCY_INVERTER * EFFICIENCY_COOLING * EFFICIENCY_TRANSFORMER * EFFICIENCY_DISTRIBUTION
EFFICIENCY_SYS = EFFICIENCY_BAT * EFFICIENCY_REST

## Degradation
BATTERY_DEGRADATION_CAL_VALUE = INITIAL_BATTERY_CAPACITY * 0.0033041117323577 / 100 / 96 #pro 15min 
EFFICIENCY_DEGRADATION_CAL_VALUE = (2.714 * 10**(-6) / 100) * EFFICIENCY_BAT
SOC_FACTORS = {0: 1.60, 1: 1.00, 2: 1.02, 3: 1.20}


## Einmalige Investitionskosten (CAPEX)
BATTERY_INVEST = 999000  #  
INVERTER_INVEST = 112125  #

AUX_TRAFO_INVEST = 15000
ARRAY_MODULE_INVEST = 36225
DC_REST_INVEST = AUX_TRAFO_INVEST + ARRAY_MODULE_INVEST

TRANSFORMER_INVEST = 150000 #
FUNDAMENT_INVEST = 37000

CONSTRUCTION_ALLOWANCE_INVEST = 50000 * SYSTEM_POWER  # € z.B. zwischen 50-100k€; Quelle Torsten Batterieinfos
GRID_CONNECTION_INVEST = 50000  # geschätzt (Sicher 7479 für Transport)
INSURANCE_EXTENSION  = 73529


## Laufende Betriebskosten (OPEX, jährlich)

INSURANCE_RATE = 0.01  # % der Investitionskosten (abzüglich CONSTRUCTION_ALLOWANCE_INVEST)
OPEX_COST = 12000 * SYSTEM_POWER #pro Jahr #Technical Management + Maintenance + Repairs + Measurements + Accounting 

## Taxes
TAX_RATE = 0.20 # % 
DEPRECIATION_YEARS = 10 #Abschreibungsdauer in Jahren


#Regelleistungsmarkt Config PROFIT_FACTOR_SRL_POS = 1.5
PROFIT_FACTOR_SRL_NEG = 1
PROFIT_FACTOR_SRL_POS = 1.6 #Faktor für die positive Regelleistung

#Märkte
MARKET_SWITCH = 1
PRL_SWITCH = 1
SRL_SWITCH = 1

#Cycles
MAX_CYCLES_PER_DAY = 0 # 0 oder None keine Begrenzung







