#Export Config
RESULTS_DIR = Path("results")
FILE_NAME = f"results_market-{MARKET_SWITCH}_prl-{PRL_SWITCH}_srl-{SRL_SWITCH}_{BAT_CAPACITY}-MWH_{SYSTEM_POWER}MW_{BAT_PRICE}€_LC-{LIFETIME_CYCLES}n_n-{EFFICIENCY}%_{START_DATE}to{END_DATE}"
RESULTS_FILE_NAME_EXCEL =  f"{FILE_NAME}.xlsx"
RESULTS_FILE_NAME_PICKLE = f"{FILE_NAME}.pkl"